---
name: CI on PR

on:
  pull_request:

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
        with:
          configFile: commitlintrc.json

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get Nix version
        id: nix-version
        run: echo "version=$(cat .nix-version)" >> $GITHUB_OUTPUT
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-${{ steps.nix-version.outputs.version }}/install
      - name: run cargo test
        run: nix develop -c cargo test --all-features

  formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get Nix version
        id: nix-version
        run: echo "version=$(cat .nix-version)" >> $GITHUB_OUTPUT
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-${{ steps.nix-version.outputs.version }}/install
      - name: running cargo fmt
        run: |
          cargo fmt --check
